name: 'rust-cargo-install'
description: 'Install a Rust binary as fast as possible'
author: 'actions-rs team'
branding:
  icon: play-circle
  color: black
inputs:
  crate:
    description: Binary crate name
    required: true
  version:
    description: Specify a version to install
    required: false
    default: 'latest'
  use-cache:
    description: Store installed binary in the GitHub Actions cache
    required: false
    default: 'true'
  bins:
    description: The specific binaries in the crate to be installed
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
